name: pokedex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  build_runner: ^2.3.3
  json_annotation: ^4.7.0
  cached_network_image: ^3.2.3
  dio: ^5.9.0
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.3
  audioplayers: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.5.4
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/loading.gif
